/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all of your component files.
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  safelist: [
    {
      pattern: /^text-/,
    },
    {
      pattern: /^bg-/,
    },
  ],
  theme: {
    extend: {
      colors: {
        border: "rgb(var(--border))",
        input: "rgb(var(--input))",
        ring: "rgb(var(--ring))",
        background: "rgb(var(--background))",
        foreground: "rgb(var(--foreground))",
        // background: {
        //   0: "rgb(var(--color-background-0)/<alpha-value>)",
        //   50: "rgb(var(--color-background-50)/<alpha-value>)",
        //   100: "rgb(var(--color-background-100)/<alpha-value>)",
        //   200: "rgb(var(--color-background-200)/<alpha-value>)",
        //   300: "rgb(var(--color-background-300)/<alpha-value>)",
        //   400: "rgb(var(--color-background-400)/<alpha-value>)",
        //   500: "rgb(var(--color-background-500)/<alpha-value>)",
        //   600: "rgb(var(--color-background-600)/<alpha-value>)",
        //   700: "rgb(var(--color-background-700)/<alpha-value>)",
        //   800: "rgb(var(--color-background-800)/<alpha-value>)",
        //   900: "rgb(var(--color-background-900)/<alpha-value>)",
        //   950: "rgb(var(--color-background-950)/<alpha-value>)",
        //   danger: "rgb(var(--color-background-danger)/<alpha-value>)",
        //   warning: "rgb(var(--color-background-warning)/<alpha-value>)",
        //   muted: "rgb(var(--color-background-muted)/<alpha-value>)",
        //   success: "rgb(var(--color-background-success)/<alpha-value>)",
        //   info: "rgb(var(--color-background-info)/<alpha-value>)",
        //   light: "#FBFBFB",
        //   dark: "#181719",
        // },

        primary: {
          DEFAULT: "rgb(var(--primary))",
          foreground: "rgb(var(--primary-foreground))",
          0: "rgb(var(--color-primary-0)/<alpha-value>)",
          50: "rgb(var(--color-primary-50)/<alpha-value>)",
          100: "rgb(var(--color-primary-100)/<alpha-value>)",
          200: "rgb(var(--color-primary-200)/<alpha-value>)",
          300: "rgb(var(--color-primary-300)/<alpha-value>)",
          400: "rgb(var(--color-primary-400)/<alpha-value>)",
          500: "rgb(var(--color-primary-500)/<alpha-value>)",
          600: "rgb(var(--color-primary-600)/<alpha-value>)",
          700: "rgb(var(--color-primary-700)/<alpha-value>)",
          800: "rgb(var(--color-primary-800)/<alpha-value>)",
          900: "rgb(var(--color-primary-900)/<alpha-value>)",
          950: "rgb(var(--color-primary-950)/<alpha-value>)",
        },
        secondary: {
          DEFAULT: "rgb(var(--secondary))",
          foreground: "rgb(var(--secondary-foreground))",
          0: "rgb(var(--color-secondary-0)/<alpha-value>)",
          50: "rgb(var(--color-secondary-50)/<alpha-value>)",
          100: "rgb(var(--color-secondary-100)/<alpha-value>)",
          200: "rgb(var(--color-secondary-200)/<alpha-value>)",
          300: "rgb(var(--color-secondary-300)/<alpha-value>)",
          400: "rgb(var(--color-secondary-400)/<alpha-value>)",
          500: "rgb(var(--color-secondary-500)/<alpha-value>)",
          600: "rgb(var(--color-secondary-600)/<alpha-value>)",
          700: "rgb(var(--color-secondary-700)/<alpha-value>)",
          800: "rgb(var(--color-secondary-800)/<alpha-value>)",
          900: "rgb(var(--color-secondary-900)/<alpha-value>)",
          950: "rgb(var(--color-secondary-950)/<alpha-value>)",
        },
        destructive: {
          DEFAULT: "rgb(var(--destructive))",
          foreground: "rgb(var(--destructive-foreground))",
        },
        tertiary: {
          DEFAULT: "rgb(var(--color-tertiary-500))",
          50: "rgb(var(--color-tertiary-50)/<alpha-value>)",
          100: "rgb(var(--color-tertiary-100)/<alpha-value>)",
          200: "rgb(var(--color-tertiary-200)/<alpha-value>)",
          300: "rgb(var(--color-tertiary-300)/<alpha-value>)",
          400: "rgb(var(--color-tertiary-400)/<alpha-value>)",
          500: "rgb(var(--color-tertiary-500)/<alpha-value>)",
          600: "rgb(var(--color-tertiary-600)/<alpha-value>)",
          700: "rgb(var(--color-tertiary-700)/<alpha-value>)",
          800: "rgb(var(--color-tertiary-800)/<alpha-value>)",
          900: "rgb(var(--color-tertiary-900)/<alpha-value>)",
          950: "rgb(var(--color-tertiary-950)/<alpha-value>)",
        },
        danger: {
          DEFAULT: "rgb(var(--color-danger-500))",
          0: "rgb(var(--color-danger-0)/<alpha-value>)",
          50: "rgb(var(--color-danger-50)/<alpha-value>)",
          100: "rgb(var(--color-danger-100)/<alpha-value>)",
          200: "rgb(var(--color-danger-200)/<alpha-value>)",
          300: "rgb(var(--color-danger-300)/<alpha-value>)",
          400: "rgb(var(--color-danger-400)/<alpha-value>)",
          500: "rgb(var(--color-danger-500)/<alpha-value>)",
          600: "rgb(var(--color-danger-600)/<alpha-value>)",
          700: "rgb(var(--color-danger-700)/<alpha-value>)",
          800: "rgb(var(--color-danger-800)/<alpha-value>)",
          900: "rgb(var(--color-danger-900)/<alpha-value>)",
          950: "rgb(var(--color-danger-950)/<alpha-value>)",
        },
        success: {
          DEFAULT: "rgb(var(--color-success-500))",
          0: "rgb(var(--color-success-0)/<alpha-value>)",
          50: "rgb(var(--color-success-50)/<alpha-value>)",
          100: "rgb(var(--color-success-100)/<alpha-value>)",
          200: "rgb(var(--color-success-200)/<alpha-value>)",
          300: "rgb(var(--color-success-300)/<alpha-value>)",
          400: "rgb(var(--color-success-400)/<alpha-value>)",
          500: "rgb(var(--color-success-500)/<alpha-value>)",
          600: "rgb(var(--color-success-600)/<alpha-value>)",
          700: "rgb(var(--color-success-700)/<alpha-value>)",
          800: "rgb(var(--color-success-800)/<alpha-value>)",
          900: "rgb(var(--color-success-900)/<alpha-value>)",
          950: "rgb(var(--color-success-950)/<alpha-value>)",
        },
        warning: {
          DEFAULT: "rgb(var(--color-warning-500))",
          0: "rgb(var(--color-warning-0)/<alpha-value>)",
          50: "rgb(var(--color-warning-50)/<alpha-value>)",
          100: "rgb(var(--color-warning-100)/<alpha-value>)",
          200: "rgb(var(--color-warning-200)/<alpha-value>)",
          300: "rgb(var(--color-warning-300)/<alpha-value>)",
          400: "rgb(var(--color-warning-400)/<alpha-value>)",
          500: "rgb(var(--color-warning-500)/<alpha-value>)",
          600: "rgb(var(--color-warning-600)/<alpha-value>)",
          700: "rgb(var(--color-warning-700)/<alpha-value>)",
          800: "rgb(var(--color-warning-800)/<alpha-value>)",
          900: "rgb(var(--color-warning-900)/<alpha-value>)",
          950: "rgb(var(--color-warning-950)/<alpha-value>)",
        },
        info: {
          DEFAULT: "rgb(var(--color-info-500))",
          0: "rgb(var(--color-info-0)/<alpha-value>)",
          50: "rgb(var(--color-info-50)/<alpha-value>)",
          100: "rgb(var(--color-info-100)/<alpha-value>)",
          200: "rgb(var(--color-info-200)/<alpha-value>)",
          300: "rgb(var(--color-info-300)/<alpha-value>)",
          400: "rgb(var(--color-info-400)/<alpha-value>)",
          500: "rgb(var(--color-info-500)/<alpha-value>)",
          600: "rgb(var(--color-info-600)/<alpha-value>)",
          700: "rgb(var(--color-info-700)/<alpha-value>)",
          800: "rgb(var(--color-info-800)/<alpha-value>)",
          900: "rgb(var(--color-info-900)/<alpha-value>)",
          950: "rgb(var(--color-info-950)/<alpha-value>)",
        },
        typography: {
          0: "rgb(var(--color-typography-0)/<alpha-value>)",
          50: "rgb(var(--color-typography-50)/<alpha-value>)",
          100: "rgb(var(--color-typography-100)/<alpha-value>)",
          200: "rgb(var(--color-typography-200)/<alpha-value>)",
          300: "rgb(var(--color-typography-300)/<alpha-value>)",
          400: "rgb(var(--color-typography-400)/<alpha-value>)",
          500: "rgb(var(--color-typography-500)/<alpha-value>)",
          600: "rgb(var(--color-typography-600)/<alpha-value>)",
          700: "rgb(var(--color-typography-700)/<alpha-value>)",
          800: "rgb(var(--color-typography-800)/<alpha-value>)",
          900: "rgb(var(--color-typography-900)/<alpha-value>)",
          950: "rgb(var(--color-typography-950)/<alpha-value>)",
          white: "#FFFFFF",
          gray: "#D4D4D4",
          black: "#181718",
        },
        outline: {
          0: "rgb(var(--color-outline-0)/<alpha-value>)",
          50: "rgb(var(--color-outline-50)/<alpha-value>)",
          100: "rgb(var(--color-outline-100)/<alpha-value>)",
          200: "rgb(var(--color-outline-200)/<alpha-value>)",
          300: "rgb(var(--color-outline-300)/<alpha-value>)",
          400: "rgb(var(--color-outline-400)/<alpha-value>)",
          500: "rgb(var(--color-outline-500)/<alpha-value>)",
          600: "rgb(var(--color-outline-600)/<alpha-value>)",
          700: "rgb(var(--color-outline-700)/<alpha-value>)",
          800: "rgb(var(--color-outline-800)/<alpha-value>)",
          900: "rgb(var(--color-outline-900)/<alpha-value>)",
          950: "rgb(var(--color-outline-950)/<alpha-value>)",
        },
        indicator: {
          primary: "rgb(var(--color-indicator-primary)/<alpha-value>)",
          info: "rgb(var(--color-indicator-info)/<alpha-value>)",
          danger: "rgb(var(--color-indicator-danger)/<alpha-value>)",
        },
        muted: {
          DEFAULT: "rgb(var(--muted))",
          foreground: "rgb(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "rgb(var(--accent))",
          foreground: "rgb(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "rgb(var(--popover))",
          foreground: "rgb(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "rgb(var(--card))",
          foreground: "rgb(var(--card-foreground))",
        },

        /* Landing page palette */
        "page-bg": "rgb(var(--color-page-bg) / <alpha-value>)",
        "panel-bg": "rgb(var(--color-panel-bg) / <alpha-value>)",
        heading: "rgb(var(--color-heading) / <alpha-value>)",
        subtext: "rgb(var(--color-subtext) / <alpha-value>)",
        "accent-green": {
          DEFAULT: "rgb(var(--color-accent-green) / <alpha-value>)",
          light: "rgb(var(--color-accent-green-light) / <alpha-value>)",
        },
        "card-glass": "rgb(var(--color-card-glass) / <alpha-value>)",
        "card-border": "rgb(var(--color-card-border) / <alpha-value>)",
        "hero-card": "rgb(var(--color-hero-card) / <alpha-value>)",
        "hero-card-border": "rgb(var(--color-hero-card-border) / <alpha-value>)",
        "hero-label": "rgb(var(--color-hero-label) / <alpha-value>)",
        "hero-amount": "rgb(var(--color-hero-amount) / <alpha-value>)",
        "float-card": "rgb(var(--color-float-card) / <alpha-value>)",
        "float-card-border": "rgb(var(--color-float-card-border) / <alpha-value>)",
        "float-text": "rgb(var(--color-float-text) / <alpha-value>)",
        "badge-bg": "rgb(var(--color-badge-bg) / <alpha-value>)",
        "badge-border": "rgb(var(--color-badge-border) / <alpha-value>)",
        "badge-text": "rgb(var(--color-badge-text) / <alpha-value>)",
        "bar-primary": "rgb(var(--color-bar-primary) / <alpha-value>)",
        "bar-accent": "rgb(var(--color-bar-accent) / <alpha-value>)",
        "heading-grad-start": "rgb(var(--color-heading-grad-start) / <alpha-value>)",
        "heading-grad-end": "rgb(var(--color-heading-grad-end) / <alpha-value>)",
        "mode-card-bg": "rgb(var(--color-mode-card-bg) / <alpha-value>)",
        "mode-card-border": "rgb(var(--color-mode-card-border) / <alpha-value>)",
        "mode-title": "rgb(var(--color-mode-title) / <alpha-value>)",
        "mode-desc": "rgb(var(--color-mode-desc) / <alpha-value>)",
        hint: "rgb(var(--color-hint) / <alpha-value>)",
        "toggle-track": "rgb(var(--color-toggle-track) / <alpha-value>)",
        "toggle-knob": "rgb(var(--color-toggle-knob) / <alpha-value>)",
        "toggle-label": "rgb(var(--color-toggle-label) / <alpha-value>)",
        "toggle-bg": "rgb(var(--color-toggle-bg) / <alpha-value>)",
        "toggle-border": "rgb(var(--color-toggle-border) / <alpha-value>)",
        "trust-icon": "rgb(var(--color-trust-icon) / <alpha-value>)",
        "trust-text": "rgb(var(--color-trust-text) / <alpha-value>)",
        "feature-icon-border": "rgb(var(--color-feature-icon-border) / <alpha-value>)",
        "feature-text": "rgb(var(--color-feature-text) / <alpha-value>)",
        "stat-card-bg": "rgb(var(--color-stat-card-bg) / <alpha-value>)",
        "stat-border": "rgb(var(--color-stat-border) / <alpha-value>)",
        "stat-label": "rgb(var(--color-stat-label) / <alpha-value>)",
        "stat-value": "rgb(var(--color-stat-value) / <alpha-value>)",
        "grid-line": "rgb(var(--color-grid) / <alpha-value>)",
      },
      fontFamily: {
        heading: undefined,
        body: undefined,
        mono: undefined,
        roboto: ["Roboto", "sans-serif"],
      },
      fontWeight: {
        extrablack: "950",
      },
      fontSize: {
        "2xs": "10px",
      },
      boxShadow: {
        "hard-1": "-2px 2px 8px 0px rgba(38, 38, 38, 0.20)",
        "hard-2": "0px 3px 10px 0px rgba(38, 38, 38, 0.20)",
        "hard-3": "2px 2px 8px 0px rgba(38, 38, 38, 0.20)",
        "hard-4": "0px -3px 10px 0px rgba(38, 38, 38, 0.20)",
        "hard-5": "0px 2px 10px 0px rgba(38, 38, 38, 0.10)",
        "soft-1": "0px 0px 10px rgba(38, 38, 38, 0.1)",
        "soft-2": "0px 0px 20px rgba(38, 38, 38, 0.2)",
        "soft-3": "0px 0px 30px rgba(38, 38, 38, 0.1)",
        "soft-4": "0px 0px 40px rgba(38, 38, 38, 0.1)",
      },
    },
  },
  plugins: [],
};
