import { appSchema, tableSchema } from "@nozbe/watermelondb";

export const schema = appSchema({
  version: 2, // Increment version for schema change
  tables: [
    tableSchema({
      name: "account_categories",
      columns: [
        { name: "Name", type: "string" },
        { name: "Type", type: "string" }, // Asset, Liability
        { name: "Color", type: "string" },
        { name: "Icon", type: "string" },
        { name: "DisplayOrder", type: "number" },
        { name: "TenantId", type: "string" },
        { name: "IsDeleted", type: "boolean" },
        { name: "CreatedAt", type: "number" },
        { name: "CreatedBy", type: "string", isOptional: true },
        { name: "UpdatedAt", type: "number" },
        { name: "UpdatedBy", type: "string", isOptional: true },
      ],
    }),
    tableSchema({
      name: "accounts",
      columns: [
        { name: "Name", type: "string" },
        { name: "CategoryId", type: "string", isIndexed: true },
        { name: "Balance", type: "number" },
        { name: "Currency", type: "string" },
        { name: "Color", type: "string" },
        { name: "Icon", type: "string" },
        { name: "Description", type: "string", isOptional: true },
        { name: "Notes", type: "string", isOptional: true },
        { name: "Owner", type: "string", isOptional: true },
        { name: "DisplayOrder", type: "number" },
        { name: "TenantId", type: "string" },
        { name: "IsDeleted", type: "boolean" },
        { name: "CreatedAt", type: "number" },
        { name: "CreatedBy", type: "string", isOptional: true },
        { name: "UpdatedAt", type: "number" },
        { name: "UpdatedBy", type: "string", isOptional: true },
      ],
    }),
    tableSchema({
      name: "transaction_groups",
      columns: [
        { name: "Name", type: "string" },
        { name: "Type", type: "string" }, // Expense, Income, Transfer, Adjustment, Initial, Refund
        { name: "Color", type: "string" },
        { name: "Icon", type: "string" },
        { name: "Description", type: "string", isOptional: true },
        { name: "DisplayOrder", type: "number" },
        { name: "BudgetAmount", type: "number" },
        { name: "BudgetFrequency", type: "string" },
        { name: "TenantId", type: "string" },
        { name: "IsDeleted", type: "boolean" },
        { name: "CreatedAt", type: "number" },
        { name: "CreatedBy", type: "string", isOptional: true },
        { name: "UpdatedAt", type: "number" },
        { name: "UpdatedBy", type: "string", isOptional: true },
      ],
    }),
    tableSchema({
      name: "transaction_categories",
      columns: [
        { name: "Name", type: "string", isOptional: true },
        { name: "GroupId", type: "string", isIndexed: true },
        { name: "Type", type: "string" }, // Expense, Income, Transfer, Adjustment, Initial, Refund
        { name: "Color", type: "string" },
        { name: "Icon", type: "string" },
        { name: "Description", type: "string", isOptional: true },
        { name: "DisplayOrder", type: "number" },
        { name: "BudgetAmount", type: "number" },
        { name: "BudgetFrequency", type: "string" },
        { name: "TenantId", type: "string" },
        { name: "IsDeleted", type: "boolean" },
        { name: "CreatedAt", type: "number" },
        { name: "CreatedBy", type: "string", isOptional: true },
        { name: "UpdatedAt", type: "number" },
        { name: "UpdatedBy", type: "string", isOptional: true },
      ],
    }),
    tableSchema({
      name: "transactions",
      columns: [
        { name: "Name", type: "string", isOptional: true },
        { name: "AccountId", type: "string", isIndexed: true },
        { name: "CategoryId", type: "string", isIndexed: true },
        { name: "Amount", type: "number" },
        { name: "Date", type: "string" },
        { name: "Description", type: "string", isOptional: true },
        { name: "Payee", type: "string", isOptional: true },
        { name: "Notes", type: "string", isOptional: true },
        { name: "Tags", type: "string", isOptional: true }, // JSON string array
        { name: "Type", type: "string" }, // Expense, Income, Transfer, Adjustment, Initial, Refund
        { name: "TransferAccountId", type: "string", isOptional: true, isIndexed: true },
        { name: "TransferId", type: "string", isOptional: true, isIndexed: true },
        { name: "IsVoid", type: "boolean" },
        { name: "TenantId", type: "string" },
        { name: "IsDeleted", type: "boolean" },
        { name: "CreatedAt", type: "number" },
        { name: "CreatedBy", type: "string", isOptional: true },
        { name: "UpdatedAt", type: "number" },
        { name: "UpdatedBy", type: "string", isOptional: true },
      ],
    }),
    tableSchema({
      name: "configurations",
      columns: [
        { name: "KEY", type: "string" },
        { name: "Value", type: "string" },
        { name: "type", type: "string" },
        { name: "table", type: "string" },
        { name: "TenantId", type: "string", isOptional: true },
        { name: "IsDeleted", type: "boolean" },
        { name: "CreatedAt", type: "number" },
        { name: "CreatedBy", type: "string", isOptional: true },
        { name: "UpdatedAt", type: "number" },
        { name: "UpdatedBy", type: "string", isOptional: true },
      ],
    }),
    tableSchema({
      name: "recurrings",
      columns: [
        { name: "name", type: "string" },
        { name: "sourceaccountid", type: "string", isIndexed: true },
        { name: "categoryid", type: "string", isOptional: true, isIndexed: true },
        { name: "amount", type: "number", isOptional: true },
        { name: "Type", type: "string" }, // Expense, Income, Transfer, Adjustment, Initial, Refund
        { name: "description", type: "string", isOptional: true },
        { name: "payeename", type: "string", isOptional: true },
        { name: "notes", type: "string", isOptional: true },
        { name: "currencycode", type: "string" },
        { name: "recurrencerule", type: "string" },
        { name: "nextoccurrencedate", type: "string" },
        { name: "enddate", type: "string", isOptional: true },
        { name: "lastexecutedat", type: "string", isOptional: true },
        { name: "isactive", type: "boolean" },
        { name: "tenantid", type: "string" },
        { name: "isdeleted", type: "boolean" },
        { name: "createdat", type: "number" },
        { name: "createdby", type: "string", isOptional: true },
        { name: "updatedat", type: "number" },
        { name: "updatedby", type: "string", isOptional: true },
      ],
    }),
    tableSchema({
      name: "profiles",
      columns: [
        { name: "email", type: "string", isOptional: true },
        { name: "full_name", type: "string", isOptional: true },
        { name: "avatar_url", type: "string", isOptional: true },
        { name: "timezone", type: "string", isOptional: true },
        { name: "tenant_id", type: "string", isOptional: true },
        { name: "updated_at", type: "number" },
      ],
    }),
  ],
});
